name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
          vs: [vc15]
          arch: [x64, x86]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: 14.16
      - run: ./.github/workflows/build.ps1 -vs ${{matrix.vs}} -arch ${{matrix.arch}} -libssh2 1.9.0 -openssl 1.1.1k -zlib 1.2.11 -nghttp2 1.40.0
      - uses: actions/upload-artifact@v2
        with:
          name: libcurl-7.76.1-${{matrix.vs}}-${{matrix.arch}}
          path: ./winlib_build/
